### ISSUE TITLE
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by austinkloske22** [lemaiwo/UI5LabLibraryPDFViewer#2]
I am attempting to use a UI5Lab for the first time. Apologize if there's an obvious solution.

How am I supposed to format my base64 pdf string before passing it to the pdfSource property? In practice i have many base64 PDF strings in the HANA DB Container I'd like to preview using your UI5Lab. 

As an example below, I am attempting to pass a small hello world base64 PDF string to the controller. When mapped to a EntitySet, the PDF viewer renders the magnifier properly so I below the initial set-up is correct.

![partial-render](https://user-images.githubusercontent.com/45456027/79393311-b2093500-7f3a-11ea-914d-dd49e607af5d.png)

![db-view](https://user-images.githubusercontent.com/45456027/79392934-d87aa080-7f39-11ea-8915-af16f4103a96.png)

![PDFViewer-view-xml](https://user-images.githubusercontent.com/45456027/79392796-97828c00-7f39-11ea-95ed-da9236d2a879.png)

![error](https://user-images.githubusercontent.com/45456027/79392816-9fdac700-7f39-11ea-9211-cf806aa126f4.png)

**Comment by lemaiwo** [comment]
You have to add "data:application/pdf;base64," in front of the base64 string. This is needed to understand the base64 string. Hope this helps.
